### ISSUE TITLE
Reproduce "Incognito mode" issue

### ISSUE THREAD

**Issue by hofmannc** [hofmannc/MPDL-AutomatedTesting#12]
Please try to reproduce search issue in ff "Incognito mode".

**Comment by aapetrova** [comment]
1. Open Firefox -> Open menu -> New Private Window
2. Open qa-pubman homepage
3. Enter "test" in search box
4. Open "DIRTMAP: the geological record of dust" -> item not found
5. Open "Dielectrophoretic Ratchets" -> In Rework

I tried it in normal mode and it also causes the same issues.

**Comment by hofmannc** [comment]
informed Martin by E-Mail
