### ISSUE TITLE
Extend pool of basic testcases in Selenium

### ISSUE THREAD

**Issue by hofmannc** [hofmannc/MPDL-AutomatedTesting#15]
Since the basic testcases are already implemented, we (MB, CH) decided to extend the "basic pool" of automated tests:
The following functionalities will be included (for now in their simplest configuration - will be extended later):
Export (First step: TC will be finished with the display of Download notification - may be extended later)
Import
Citation Style Editor (edit: only changes in title are covered)
CoNE journals (only mandatory fields are covered)
CoNE authors (only mandatory fields are covered)

Relevant testcases will be provided in TestLink and updated keyword usage table.

**Comment by hofmannc** [comment]
Current version of keyword usage table:

[160920_Keyword Usage_PubMan_Selenium.xlsx](https://github.com/hofmannc/MPDL-AutomatedTesting/files/487575/160920_Keyword.Usage_PubMan_Selenium.xlsx)

**Comment by aapetrova** [comment]
Concerning test case #18 (Batch import): upload can be time consuming; it takes about 3 minutes for 25 items. I suggest we scale down the item count of the BibTeX file (350 in test specification).

Update CH 161010: at the moment we do not scale down - will maybe be relevant for continuous integration.

**Comment by aapetrova** [comment]
All test cases were implemented and integrated. Depositor test cases fail as described in #18.
