### ISSUE TITLE
Depositor cannot submit items

### ISSUE THREAD

**Issue by aapetrova** [hofmannc/MPDL-AutomatedTesting#18]
All tests related to the depositor fail, because depositor cannot access the submission page.

**Test cases:**
Easy submission of journal article, standard workflow (UC-005)
Full submission of book, standard workflow
Full submission of conference paper, simple workflow (UC-004)

**Steps to reproduce:**
1. Log in as depositor user
2. "Submission" button is missing

**Comment by hofmannc** [comment]
Testserver: qa-pubman
Testdate: 18./19.10.16
User: test_dep_stwf / taller 
Action: Access submit form
Observation: I cannot reproduce this issue, logged in with only depositor account and I had access to Submission.

**Comment by aapetrova** [comment]
Problem persists only with user test_dep; other depositor users work fine, so I'll use those instead.
