### ISSUE TITLE
Create Minimal TestPool for INGe - Jenkins evaluation

### ISSUE THREAD

**Issue by hofmannc** [hofmannc/MPDL-AutomatedTesting#23]
To be able to evaluate if automated Testpool is compatible with Jenkins, please adapt existing Testpool for testing purposes:

Precondition for this task:
-> Take existing automated testpool for PubMan 
-> create a new project in Selenium e.g. "INGe Automated Testpool" 
-> copy content of testpool for PubMan into new project
-> take this file as basis for all further steps for the INGe test project

Actions for this task:

-> please create again a new test project e.g. "INGe Jenkins Evaluation" on the basis of new INGe testpool

-> should contain max. 5 testcases, please see KWUT 
[171108_Keyword Usage_INGe_Jenkins_Test_of_Test.xlsx](https://github.com/hofmannc/MPDL-AutomatedTesting/files/1453084/171108_Keyword.Usage_INGe_Jenkins_Test_of_Test.xlsx)

please refer to existing test cases 

-> keep the testcases as "gekapselt" as possible to be able to eventually adapt testpool on the fly during the evaluation

-> If you are ready, please contact Gudrun to make first testruns on old Jenkins configuration 

-> please enter insights of this evaluation in this ticket

**Comment by aapetrova** [comment]
https://github.com/MPDL/INGeMinimalTestpool
testpool contains 2 test cases as specified in _171108_Keyword.Usage_INGe_Jenkins_Test_of_Test_
