### ISSUE TITLE
INGe Admin Tool: Evaluate strategy for Single Page Application-Testing

### ISSUE THREAD

**Issue by hofmannc** [hofmannc/MPDL-AutomatedTesting#24]
Please evaluate best solution for automated testing of INGe Admin Tool (Single Page Application/Angular JS).
- Wilhelm uses Angular Client, based on Jasmin and Karma.
- Node JS and npm
- Code in GitHub project MPDL -> PubManAdmin Tool https://github.com/MPDL/PubManAdmin

Please try to get first insights by mid of November.

**Comment by aapetrova** [comment]
The plan is to use the framework [Protractor](http://www.protractortest.org/): the test environment is already set up, we just need to design appropriate test cases.

**Comment by hofmannc** [comment]
next step: write KWUT
