### ISSUE TITLE
Keeper load tests: Install test environment on laptop

### ISSUE THREAD

**Issue by hofmannc** [hofmannc/MPDL-AutomatedTesting#28]
Please install all necessary tools to perform the load tests on Keeper on the laptop provided by Vlad.
The goal is to use only this laptop to perform the load tests.

Please be aware that environment should be up for testing on November 30.

**Comment by aapetrova** [comment]
The environment has been set up.

Tools:
- Firefox 46
- Apache JMeter 3.3
- WebDriver, SSH plugins
