### ISSUE TITLE
QA-PubMan: Run automated testpool 

### ISSUE THREAD

**Issue by hofmannc** [hofmannc/MPDL-AutomatedTesting#33]
Please run the automated testpool for PubMan on http://qa-pubman.mpdl.mpg.de/ . 

There are no major changes in the functinalities, so there should be no Selenium code changes necessary.

We should be able to give feedback about the behaviour of the system to Martin by tomorrow afternoon (14.12.)

**Comment by aapetrova** [comment]
No failures were uncovered during testing.
