### ISSUE TITLE
Failed validation of data (MARC Buch21.mrc)

### ISSUE THREAD

**Issue by aapetrova** [hofmannc/MPDL-AutomatedTesting#6]
**Issue: validation of uploaded data in format .mrc results in a failure**
The process exits normally (FINISHED), but:
- according to the logs after file import in the Import Workspace the entered value does not conform to multiple classifications (DDC, MPI PKS, etc.)
- the file is not displayed afterwards in "My Items"

Is there a specific standard for naming files? I've followed all steps in the TestLink test case.

**Comment by hofmannc** [comment]
no, there is actually no standard. Please try it with files derived from PubMan By "Export" as discussed, later on we will demand proper files from support team.

Andrea will check the given mrc file.
