### ISSUE TITLE
Manage batch deletion of discarded items after test

### ISSUE THREAD

**Issue by hofmannc** [hofmannc/MPDL-AutomatedTesting#7]
**Problem:**
QA-system gets unnecessarily overcrowded if all test items remain in the system after the testround. The deletion of unpublished items can be done by a cleanup function within the functionality of the system. But once the item is published, user only can discard the item, but not remove it from the system. Same applies for user accounts in Admin tool.

**Solution approaches:**
AP currently follows an GUI based approach.

-> Matthias Walther asked if AP implemented the batch deletion of the discarded items via GUI or PubMan ReST-API - he has a tool for the implementation by REST-API. Maybe this would be easier to implement.

**Next steps:**
AP and MW will check out the tool on Thursday 14.07.
It is AP's decision which method she is going to follow.

**Comment by aapetrova** [comment]
For now I will use a cleanup function to remove all uploaded test items and use the Admin tool in case an item cannot be completely deleted as a backup.
