### ISSUE TITLE
Manage access data in Selenium code

### ISSUE THREAD

**Issue by hofmannc** [hofmannc/MPDL-AutomatedTesting#8]
**Problem:**
The Selenium code is published in GitHub, so we must not handle valid username and passwords within the code.

**Solution approaches:**
a) 
- For each release we create manually 3 new users in admin tool (depositor/moderator/depositor and moderator). The user data is defined in Selenium code.
- The Selenium code works with the user data and deletes the user after each testround.

b)
- We only create test user once.
- Selenium code works with the user data.
- We change passwords manually after the test.

c)
any alternative?

**Next steps:**
Discuss topic before implementation of first tests. (18.07.)
Load tests should also be considered.

**Comment by aapetrova** [comment]
Solved by using a new approach, in which the file containing login data is hosted on Jenkins and accessed through code.
An advantage is that we do not need to manually create new users or change passwords.
